### ISSUE TITLE
Netherite Duplication Bug Recipe

### ISSUE THREAD

**Issue by klinbee** [CodeMouse92/the-missing-recipes#2]
One of my friends was looking at your Datapack, and we realized that Stonecutter Lodestone recipe gives 3 ingots, which is funny because the Lodestone needs one ingot to craft, so it's an infinite source of netherite... Lol

**Comment by CodeMouse92** [comment]
Oh! Hah, good catch. If you want to tweak that recipe file in a Pull Request, I'd be super grateful, as I don't have a lot of time. Otherwise, I'll get to this when I can.
